# Generated by Django 5.2.17 on 2026-08-28 21:01
import phonenumbers
from django.db import migrations


def normalize_owners_phonenumber(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all().iterator():
        raw_phone_num = flat.owners_phonenumber
        try:
            parsed_phone_num = phonenumbers.parse(raw_phone_num, "RU")
            if phonenumbers.is_valid_number(parsed_phone_num):
                normalized_phonenum = phonenumbers.format_number(
                    parsed_phone_num,
                    phonenumbers.PhoneNumberFormat.E164
                )
                flat.owner_pure_phone = normalized_phonenum
                flat.save(update_fields=["owner_pure_phone"])
        except phonenumbers.phonenumberutil.NumberParseException:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_owners_phonenumber),
    ]
