# Generated by Django 5.2.17 on 2026-08-29 20:36

from django.db import migrations


def add_flats_to_owner(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    test_flats = Flat.objects.filter(owner="Сергеева Кира Робертовна")
    for flat in test_flats:
        try:
            owner = Owner.objects.get(
                name=flat.owner,
                owners_phonenumber=flat.owners_phonenumber,
            )
            owner.flats.add(flat)
        except Owner.DoesNotExist:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20260829_2205'),
    ]

    operations = [
        migrations.RunPython(add_flats_to_owner),
    ]
