# Generated by Django 5.2.17 on 2026-08-30 20:38

from django.db import migrations


def link_flats_to_owner(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    test_flats = Flat.objects.filter(owner="Чернова Евфросиния Станиславовна")
    for flat in test_flats:
        if not flat.owner or not flat.owners_phonenumber:
            continue
        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
        )
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20260829_2336'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owner),
    ]
