# Generated by Django 5.2.17 on 2026-09-03 18:22

from django.db import migrations


def link_flats_to_owner(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    flats = Flat.objects.all()
    for flat in flats:
        if not flat.owner or not flat.owners_phonenumber:
            continue
        owner, created = Owner.objects.get_or_create(
            name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
        )
        owner.flats.add(flat)


def reverse_link_flats_to_owner(apps, schema_editor):
    Owner = apps.get_model("property", "Owner")
    for owner in Owner.objects.all():
        owner.flats.clear()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20260830_2338'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owner),
    ]
