# Generated by Django 5.2.17 on 2026-09-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_remove_flat_owner_remove_flat_owners_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
    ]
