# Generated by Django 5.2.17 on 2026-09-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Новостройка'),
        ),
    ]
